### ISSUE TITLE
Groups are created but not returned in API

### ISSUE THREAD

**Issue by ppokrovsky** [wazuh/wazuh-kubernetes#218]
Hi. I'm experiencing an issue with my deployment, when agent groups are created in the API, but not returned until manager restart. Same is observed using Kibana interface. 

My deployment is using persistent volume volumeMount for /var/ossec/etc directory

When performing 
`curl -k -X POST 'https://localhost:55000/groups' -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"group_id": "Test"}'`
the output is
`{"message": "Group 'Test' created.", "error": 0}`

but `GET /groups` returns empty list of groups
`{"data": {"affected_items": [{"name": "default", "count": 0, "mergedSum": "2c45c95db2954d2c7d0ea533f09e81a5", "configSum": "ab73af41699f13fdd81903b5f23d8d00"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "All selected groups information was returned", "error": 0}`

the group `Test` is created, because when I attempt to create another group with the same name it returns error
`{"title": "Bad Request", "detail": "The group already exists: Test", "remediation": "Please, use another group ID", "dapi_errors": {"node01": {"error": "The group already exists: Test"}}, "error": 1711}`

What I observed is when I remove volumeMount for `/var/ossec/etc` things are back to normal, so I will see changes in API immediatelly. This issue only occurs when using persistentVolume.

Also If I restart wazuh-manager, then I will see all the changes in the API, but new requests will demonstrate the same behavior until another restart.

I also tried comparing `/var/ossec/etc/` directory in mounted and contained state and it looks the same (took an MD5 hash from .tar.gz), so apparently it has something to do specifically with using persistent volume.

My config looks like this
wazuh-server-deploy.yml (part of it)
```yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wazuh
  name: wazuh-server
  labels:
    app: wazuh-server
spec:
  selector:
    matchLabels:
      app: wazuh-server
  replicas: 1
  template:
    metadata:
      labels:
        app: wazuh-server
    spec:
      containers:
        - name: wazuh-server
          image: wazuh/wazuh-odfe:4.2.5
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          ports:
            - containerPort: 1514
              protocol: TCP
            - containerPort: 1515
              protocol: TCP
            - containerPort: 514
              protocol: UDP
            - containerPort: 55000
              protocol: TCP
              name: wazuh-api
          volumeMounts:
            - name: wazuh-server-data
              mountPath: /var/ossec/api/configuration
              subPath: wazuh/var/ossec/api/configuration
            - name: wazuh-server-data
              mountPath: /var/ossec/etc
              subPath: wazuh/var/ossec/etc
            - name: wazuh-server-data
              mountPath: /var/ossec/logs
              subPath: wazuh/var/ossec/logs
            - name: wazuh-server-data
              mountPath: /var/ossec/queue
              subPath: wazuh/var/ossec/queue
            - name: wazuh-server-data
              mountPath: /var/ossec/var/multigroups
              subPath: wazuh/var/ossec/var/multigroups
            - name: wazuh-server-data
              mountPath: /var/ossec/integrations
              subPath: wazuh/var/ossec/integrations
            - name: wazuh-server-data
              mountPath: /var/ossec/active-response/bin
              subPath: wazuh/var/ossec/active-response/bin
            - name: wazuh-server-data
              mountPath: /var/ossec/agentless
              subPath: wazuh/var/ossec/agentless
            - name: wazuh-server-data
              mountPath: /var/ossec/wodles
              subPath: wazuh/var/ossec/wodles
            - name: wazuh-server-data
              mountPath: /etc/filebeat
              subPath: filebeat/etc/filebeat
            - name: wazuh-server-data
              mountPath: /var/lib/filebeat
              subPath: filebeat/var/lib/filebeat
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
            - name: ELASTIC_USERNAME
              value: elastic
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-users-secret
                  key: elastic_password
      volumes:
        - name: wazuh-server-data
          persistentVolumeClaim:
            claimName: wazuh-server-data-claim
```

wazuh-server-pv.yml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-data
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/data/wazuh-data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - sol-kube-node-1
```

wazuh-server-pvc.yml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wazuh
  name: wazuh-server-data-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

Could you please assist me because I'm out of ideas at the moment?
