### ISSUE TITLE
LogCollector daemon error on init leaving inconsistencies

### ISSUE THREAD

**Issue by TheMatrix97** [wazuh/wazuh-kubernetes#242]
Hi!
I was facing an issue with a deployment I did with the image 'wazuh/wazuh-odfe:4.2.6', where logCollector daemon is failing on init `/var/ossec/bin/wazuh-modulesd start`. 
Digging a bit on the problem, and trying to run the daemon itself on foreground `/var/ossec/bin/wazuh-logcollector -d -f` I got the following error:
```bash
wazuh-logcollector[4192] logcollector.c:2670 at w_save_file_status(): CRITICAL: (1103): Could not open file 'queue/logcollector/file_status.json' due to [(2)-(No such file or directory)].
```
Creating the folder queue/logcollector solves the issue: `mkdir /var/ossec/queue/logcollector`, which in theory is already included in the official wazuh-odfe image.
All this problem seems to come from the VolumeMount of ` /var/ossec/queue` folder performed in the master and worker StatefulSets:
```yaml
volumeMounts:
  - name: wazuh-manager-master
    mountPath: /var/ossec/queue
    subPath: wazuh/var/ossec/queue
```
That makes the internal logcollector folder to disappear and throw the error... Which it's solved just adding an additional mount:

````yaml
- name: wazuh-manager-master
  mountPath: /var/ossec/queue/logcollector
  subPath: wazuh/var/ossec/queue/logcollector
````
I'm not sure if this issue is already solved in newer wazuh images, 

Just pointing that, this silly issue interrupts the wazuh init script, leaving some deaemons like wazuh-modulesd and wazuh-clusterd stopped. 
I hope it helps someone facing the same issue :)

Thanks!
