### ISSUE TITLE
Indexer pods get OOMKilled when Java options set higher than 4GB.

### ISSUE THREAD

**Issue by andraspavelbaystream** [wazuh/wazuh-kubernetes#306]
Hello,

We would like to increase the memory of the indexer pods.
The kubernetes cluster contains 3 nodes, each has 48GB Ram.
I can increase the resources limit and requests, but as soon as I go above 4GB in the OPENSEARCH_JAVA_OPTS, the pods instantly get OOMKilled.
We have 16 GB RAM allocated for the indexer pods:
```
resources:
            limits:
              cpu: 2
              memory: 16Gi
            requests:
              cpu: 1
              memory: 16Gi
```
When I increase the .. 
```
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: '-Xms4g -Xmx4g -Dlog4j2.formatMsgNoLookups=true'
```
to anything higher than 4GB, like "Xms5g -Xmx5g", all pods are getting OOMKilled instantly after creation.

![image](https://user-images.githubusercontent.com/39588110/196093638-c80c7e27-ff6a-4b5f-88e7-80d6508f8dad.png)

How can we increase the JAVA memory higher thn 4GB and avoid the crash?

Thanks,
Andras
