### ISSUE TITLE
How to set a configmap for a custom wazuh.yml config file for Kibana

### ISSUE THREAD

**Issue by sebastiandbustos** [wazuh/wazuh-kubernetes#307]
Hello team, 
We are trying to set custom passwords in GKE deployment and besides setting the passwords on the recipe we need to configure extra files with the same passwords, like the `/usr/share/kibana/data/wazuh/config/wazuh.yml`, we tried to set this with a configmap but the filesystem is showing as read only.

kustomization.yaml
```
....
  - name: kibana-conf
    files:
      - configFiles/kibana/usr/share/kibana/config/kibana.yml
      - configFiles/kibana/usr/share/kibana/data/wazuh/config/wazuh.yml
  - name: filebeat-conf
    files:
      - configFiles/filebeat/etc/filebeat/filebeat.yml
      ....
```

kibana-deploy.yaml
```
.....
    spec:
      volumes:
        - name: kibana-certs
          secret:
            secretName: kibana-certs
        - name: config-files
          configMap:
            name: kibana-conf
      containers:
        - name: wazuh-kibana
          image: 'wazuh/wazuh-kibana-odfe:4.2.6'
          lifecycle:
             postStart:
               exec:
                 command: ["/bin/bash","-c", "sleep 1 && chown -R kibana:kibana /usr/share/kibana/data/wazuh/config/wazuh.yml"]
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: kibana-certs
              mountPath: /usr/share/kibana/config/cert.pem
              readOnly: true
              subPath: cert.pem
            - name: kibana-certs
              mountPath: /usr/share/kibana/config/key.pem
              readOnly: true
              subPath: key.pem
            - name: config-files
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
              readOnly: false
            - name: config-files
              mountPath: /usr/share/kibana/data/wazuh/config/wazuh.yml
              subPath: wazuh.yml    
.....
```

The file can't be read and another is created without the proper permissions. If tried to set  the permission by setting the following:
```
          lifecycle:
             postStart:
               exec:
                 command: ["/bin/bash","-c", "sleep 1 && chown -R kibana:kibana /usr/share/kibana/data/wazuh/config/wazuh.yml"]
```

The following errors are shown:
```
Wazuh alerts template is loaded.
./wazuh_app_config.sh: line 54: /usr/share/kibana/data/wazuh/config/wazuh.yml: Permission denied
Open Distro Security not initialized.% 
```

Please let me know if you need further information. Thank you.
