### ISSUE TITLE
Duplicate alerts.

### ISSUE THREAD

**Issue by LuisGi93** [wazuh/wazuh-kubernetes#32]
Hi team,
right now duplicate alerts are found *sometimes* at least when updating from elastic stack 6.5.4 to 6.6.1.  Have tested tested with our current configuration and with the one used at SAAS:
```
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-master
              mountPath: /var/ossec/data
            - name: wazuh-manager-master
              mountPath: /etc/postfix
            - name: wazuh-manager-master
              mountPath: /var/lib/filebeat   
```
