### ISSUE TITLE
Multitenancy Doc and Support

### ISSUE THREAD

**Issue by victorrodriguez1984** [wazuh/wazuh-kubernetes#357]
Dear Team,

We can Enabled Multitenancy in a dashboard configuration easy, but there is not documentation enough to apply on Opensearch and able to use on index without multiple changes.
https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/multi-tenancy.html

Is it compatible with Opensearch in that case why this preconfig does not match `opensearch.yaml` files?
https://opensearch.org/docs/latest/security/multi-tenancy/multi-tenancy-config/

```
root@wazuh-indexer-0:/usr/share/wazuh-indexer# cat opensearch-security/config.yml 
`
[...]
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    #kibana:
    # Kibana multitenancy
    #multitenancy_enabled: true
    #server_username: kibanaserver
    #index: '.kibana'
  ```
  
  
  ```
  root@wazuh-indexer-0:/usr/share/wazuh-indexer/opensearch-security# cat tenants.yml 
---
_meta:
  type: "tenants"
  config_version: 2

# Define your tenants here

## Demo tenants
admin_tenant:
  reserved: false
  description: "Demo tenant for admin user"
root@wazuh-indexer-0:/usr/share/wazuh-indexer/opensearch-security# 
```

Doc from wazuh is not enough for real production cases
