### ISSUE TITLE
Configure Liveness and Readiness Probes for managers

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kubernetes#52]
Hello!

For Kubernetes to do its job properly, we need to define readiness and liveliness probes. For Wazuh managers, I'm thinking of [using commands](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command).

An example:
```YAML
readinessProbe:
  exec:
    command:
    - cat
    - /tmp/healthy
  initialDelaySeconds: 5
  periodSeconds: 5
```
> If the command succeeds, it returns 0, and the kubelet considers the Container to be alive and healthy. If the command returns a non-zero value, the kubelet kills the Container and restarts it.

How would you design those probes? I'm thinking of using `/var/ossec/bin/ossec-control status`, but you might have a better solution! 😄 

Thanks for the help!

**Comment by jm404** [comment]
Hi @JPLachance,

The question you raise is quite interesting. 

These checks can be tricky as `command`, as you stated, only checks the return of the executed command. 

For example, the `/var/ossec/bin/ossec-control status` does actually return `1` even if the default services are properly started

![image](https://user-images.githubusercontent.com/46649922/62682574-c57ffb80-b9bc-11e9-9f2e-e9bf6449daff.png)

As you know, our image is minified (lightweight) so it doesn't have many software tools installed by default making it challenging to create a check.

We are already testing some ideas and will let you know when we find out something.

Let me point out that, as always, community ideas and feedback are really welcome!

Thanks for contributing

Best regards

Jose

**Comment by JPLachance** [comment]
Good morning!

`/var/ossec/bin/ossec-control status` never `exit 1`, but `grep` could :)

```SHELL
root@wazuh-master-0:/# /var/ossec/bin/ossec-control status | grep "not running" && echo "error" || echo "success"
ossec-maild not running...
error
```
Replace `echo "error"` by `exit 1` and I think it could work.

Now, how can I exclude `ossec-maild` from the `ossec-control status`? I did not setup `ossec-maild` because I don't need it.

So I ended up with that tiny Python script that does what I want:
```PYTHON
#!/usr/bin/env python3

import subprocess

services_to_query = [
    "wazuh-manager",
    "wazuh-api",
    "filebeat"
]

output = ""

for service in services_to_query:
    p = subprocess.Popen(["service", service, "status"], stdout=subprocess.PIPE)
    out, err = p.communicate()

    output = output + out.decode("utf-8").lower()

wazuh_manager_services = [
    "wazuh-clusterd",
    "wazuh-modulesd",
    "ossec-monitord",
    "ossec-logcollector",
    "ossec-remoted",
    "ossec-syscheckd",
    "ossec-analysisd",
    "ossec-execd",
    "wazuh-db",
    "ossec-authd",
    "wazuh-api",
    "filebeat"
]

for service in wazuh_manager_services:
    assert f"{service} is running" in output
```

Kind regards,

Jean-Philippe

**Comment by JPLachance** [comment]
Take 2!

I made my script "start" the service if it is not running as expected (helps with https://github.com/wazuh/wazuh-docker/issues/222):
```PYTHON
#!/usr/bin/env python3

import logging
import subprocess
from typing import List

SERVICES_TO_QUERY = {
    "wazuh-manager": [
        "wazuh-clusterd",
        "wazuh-modulesd",
        "ossec-monitord",
        "ossec-logcollector",
        "ossec-remoted",
        "ossec-syscheckd",
        "ossec-analysisd",
        "ossec-execd",
        "wazuh-db",
        "ossec-authd",
    ],
    "wazuh-api": [
        "wazuh-api",
    ],
    "filebeat": [
        "filebeat",
    ],
}


def query_service_status(service_name: str) -> str:
    p = subprocess.Popen(["service", service_name, "status"], stdout=subprocess.PIPE)
    out, err = p.communicate()

    return out.decode("utf-8").lower()


def assert_service_healthy(statuses: str, to_check: List[str]) -> bool:
    healthy = True

    for some_service in to_check:
        if f"{some_service} is running" not in statuses:
            logging.warning("The service %s is expected to be running but is not", some_service)
            healthy = False

    return healthy


def start_service(service_name: str) -> str:
    p = subprocess.Popen(["service", service_name, "start"], stdout=subprocess.PIPE)
    out, err = p.communicate()

    if err:
        logging.error("Failed to start the service %s: %s", service_name, err)

    return out.decode("utf-8").lower()


for service in SERVICES_TO_QUERY.keys():
    if not assert_service_healthy(query_service_status(service), SERVICES_TO_QUERY[service]):
        start_service(service)

    if not assert_service_healthy(query_service_status(service), SERVICES_TO_QUERY[service]):
        raise Exception(f"The service {service} is not running properly and auto-healing failed.")
```

I added that script in the wazuh-manager Docker image (on my machine). Then, in my YAML files:
```DIFF
             limits:
               cpu: '@(master_deploy_resources.limit_cpu)'
               memory: '@(master_deploy_resources.limit_memory)'
+          livenessProbe:
+            exec:
+              command:
+                - /health_check.py
+            initialDelaySeconds: 300
+          readinessProbe:
+            exec:
+              command:
+                - /health_check.py
+            initialDelaySeconds: 240
           env:
             - name: API_USER
               valueFrom:
```

I deployed this in my development environment and so far so good!

Kind regards,

Jean-Philippe Lachance

**Comment by jm404** [comment]
Our team came up with some ideas, I did little tweaks to use our Docker ENV variables:

```
#!/usr/bin/env python3

import logging
import subprocess
from typing import List
import sys
import os

SERVICES_TO_QUERY = {
    "wazuh-manager": [
        "wazuh-clusterd",
        "wazuh-modulesd",
        "ossec-monitord",
        "ossec-logcollector",
        "ossec-remoted",
        "ossec-syscheckd",
        "ossec-analysisd",
        "ossec-execd",
        "wazuh-db",
        "ossec-authd",
    ],
    "wazuh-api": [
        "wazuh-api",
    ],
    "filebeat": [
        "filebeat",
    ],
}

wazuh_manager_version = 'v' + os.environ['WAZUH_MANAGER'][:-2]
system = os.getenv('os')


def test_check_version():
    f = open('/var/ossec/etc/ossec-init.conf', 'r')
    version = wazuh_manager_version
    if version == '3.0.0':
      system_name = system.split()[0]
      if system_name == "ubuntu" or system_name == "debian":
        version = '3.0.1'
    assert version in f.read()
    f.close()

def test_check_ruleset_version():
    f = open('/var/ossec/ruleset/VERSION', 'r')
    major_minor = wazuh_manager_version[:-2]
    assert major_minor in f.read()
    f.close()

# Related to monitord

def test_connection_manager():
    f = open('/var/ossec/logs/alerts/alerts.log', 'r')
    assert "Ossec agent started." in f.read()
    f.close()

def query_service_status(service_name: str) -> str:
    p = subprocess.Popen(["service", service_name, "status"], stdout=subprocess.PIPE)
    out, err = p.communicate()

    return out.decode("utf-8").lower()

def assert_service_healthy(statuses: str, to_check: List[str]) -> bool:
    healthy = True

    for some_service in to_check:
        if f"{some_service} is running" not in statuses:
            logging.warning("The service %s is expected to be running but is not", some_service)
            healthy = False

    return healthy


def start_service(service_name: str) -> str:
    p = subprocess.Popen(["service", service_name, "start"], stdout=subprocess.PIPE)
    out, err = p.communicate()

    if err:
        logging.error("Failed to start the service %s: %s", service_name, err)

    return out.decode("utf-8").lower()


for service in SERVICES_TO_QUERY.keys():
    if not assert_service_healthy(query_service_status(service), SERVICES_TO_QUERY[service]):
        start_service(service)

    if not assert_service_healthy(query_service_status(service), SERVICES_TO_QUERY[service]):
        raise Exception(f"The service {service} is not running properly and auto-healing failed.")



```

That would allow to ensure versioning on managers and verify the ruleset version. Also checking the `monitord` logs to check if the connection of the Manager was properly set up.

Hope this helps or inspires new ideas!

Best regards

Jose

**Comment by xr09** [comment]
Hi there @JPLachance !

I know this is old but I've been working on this front lately and I think I have a few ideas to share.

Recently we implemented image validation on Github Actions with a tool called [Goss](https://github.com/aelsabbahy/goss) which is a ServerSpec alternative implemented in Go (no deps, really fast and easy to use). The [relevant issue](https://github.com/wazuh/wazuh-docker/issues/423) and the [goss.yaml](https://github.com/wazuh/wazuh-docker/blob/master/.goss.yaml) we are using right now on the Actions pipeline.


The thing is I believe this same tool is the solution for this issue, I've been tinkering for a few days on the best way to implement this. I could add the goss binary and add a service to s6-overlay to serve a `healthz` endpoint (this can be done with `goss -g goss.yaml serve`).

But I don't want to bake a "kubernetes only" feature into the Docker image so I was thinking of an initContainer hack to download the goss binary to a volume and execute it from there but that would add another dependency to the deployment phase (github), which I'm not happy about and of course it would be downright ugly from a design perspective.

So the option I'm pondering right now is to just add the `goss` binary to the image and use it both on Docker and Kubernetes deployments:

On a docker-compose:

```yaml
  wazuh:
    build:  wazuh-odfe/
    image: wazuh/wazuh-odfe:dev-version
    hostname: wazuh-manager
    restart: unless-stopped
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    ...
    volumes:
      ...
      - ./liveness.yaml:/var/goss/liveness.yaml
    healthcheck:
      test: /usr/local/bin/goss -g /var/goss/liveness.yaml validate
      interval: "20s"
      timeout: "3s"
      start_period: "20s"
      retries: 1
```

![2021-02-12_14-23](https://user-images.githubusercontent.com/1380243/107773397-e3f74d80-6d3d-11eb-8964-aefb7c599238.png)


On Kubernetes:

```yaml
livenessProbe:
      exec:
        command:
        - /usr/local/bin/goss
        - '-g'
        - '/var/goss/liveness.yaml'
        -  'validate'
      initialDelaySeconds: 20
      periodSeconds: 20
```

The `liveness.yaml` file could be mounted with a bind mount on Docker and a configMap on Kubernetes.


`liveness.yaml`

```yaml
port:
  tcp:1544:
    listening: true
    ip:
    - 0.0.0.0
  tcp:1515:
    listening: true
    ip:
    - 0.0.0.0
  tcp:55000:
    listening: true
    ip:
    - 0.0.0.0
process:
  filebeat:
    running: true
  ossec-analysisd:
    running: true
  ossec-authd:
    running: true
  ossec-execd:
    running: true
  ossec-monitord:
    running: true
  ossec-remoted:
    running: true
  ossec-syscheckd:
    running: true
  s6-supervise:
    running: true
  wazuh-db:
    running: true
  wazuh-modulesd:
    running: true
```


Let me know your thoughts on this @JPLachance, any feedback is appreciated!
