### ISSUE TITLE
Agent delivery on port 1514 is only exposed for worker nodes

### ISSUE THREAD

**Issue by dlouzan** [wazuh/wazuh-kubernetes#547]
According to <https://documentation.wazuh.com/4.7/user-manual/configuring-cluster/advanced-settings.html>, agent events delivery on port 1514 can be served from both the master and the workers.

But the setup in this repository makes it so that the workers service that exposes port 1514 <https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh/wazuh_managers/wazuh-workers-svc.yaml> only delivers data to the workers:

```yaml
  selector:
    app: wazuh-manager
    node-type: worker
```

Is this intended or a bug?

Thanks!
