### ISSUE TITLE
Wazuh managers cluster in Kubernetes behind an AWS Application Load Balancer?

### ISSUE THREAD

**Issue by shrivastavshubham34** [wazuh/wazuh-kubernetes#62]
I'm trying to deploy the Wazuh server in Kubernetes (I'm using your wazuh Kubernetes repo for reference). 
From there, I want to expose the Wazuh server to make it available for my other EC2 instances that are not part of my Kubernetes cluster. To do so, I'm creating an ALB Ingress Service to point to my Wazuh NodePort service at 1515 and 55000.

My Service looks like this: 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: wazuh
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: NodePort
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: api
      port: 55000
      targetPort: 55000
```
ALB configuration looks like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-ingress
  namespace: wazuh
data:
  annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
```

And Ingress looks something like this
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wazuh-manager
  namespace: wazuh
  labels:
    app: wazuh-manager
  annotations:
    kubernetes.io/ingress.class: merge
    merge.ingress.kubernetes.io/config: monitoring-ingress
spec:
  rules:
    - host: wazuhmanager.nonprod.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: wazuh
              servicePort: 55000
```
My AWS ALB works fine for other non wazuh services.
![image](https://user-images.githubusercontent.com/13406071/66170346-c6b65900-e5f8-11e9-8cfd-c168c8cfc939.png)

But somehow, I keep getting a 502 Bad Gateway from the URL everytime I try to hit my wazuh ingress endpoint.
I tried to do tcpdump over my k8s nodes and did not see any 502 related information. 
 
![image](https://user-images.githubusercontent.com/13406071/66169970-1a27a780-e5f7-11e9-836a-57fbe01447c6.png)

If I skip the Ingress installation and setup my wazuh service as LoadBalancer it works without any problems. 
The difference I see while using LoadBalancer wazuh service is the Listener
![image](https://user-images.githubusercontent.com/13406071/66170200-206a5380-e5f8-11e9-9a00-e324774103a8.png)

**ALB does not support TCP listeners**. Is this what is stopping my other EC2 (wazuh agent) instances that are not part of my Kubernetes cluster to communicate to wazuh server?
