### ISSUE TITLE
Cannot access wazuh-workers ELB service

### ISSUE THREAD

**Issue by Born2Bake** [wazuh/wazuh-kubernetes#93]
Hi,

We deployed wazuh cluster on kube in AWS. It used to work fine, however, now we are getting weird issue - wazuh agents cant connect to wazuh-worker ELB service.

```
telnet internal-.elb.amazonaws.com 1514
Trying 172.31.85.91...
Connected to internal-.eu-west-1.elb.amazonaws.com.
Escape character is '^]'.
Connection closed by foreign host.

&&&&&&&&&&&&

2020/07/13 14:51:06 ossec-agentd: INFO: Trying to connect to server (internal-.eu-west-1.elb.amazonaws.com./172.31.61.123:1514/tcp).
2020/07/13 14:51:06 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'internal-.eu-west-1.elb.amazonaws.com./172.31.61.123'.
```
LB config:
```
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
  labels:
    app: wazuh-manager
    # dns: route53
  annotations:
    # domainName: 'wazuh-manager.some-domain.com'  # TODO: Change this for a Hosted Zone you configured in AWS Route 53
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
```

Thus, wazuh cluster / manager is working fine. I can register new agents if needed but they cannot talk to workers-svc. Sec. groups should not be an issue since everything can be reached except workers-svc. Any suggestion on that one please?

**Comment by chowmean** [comment]
Can you share the ossec config?

This can be because of below
1. I hope you are aware that registration url and logs url are different. 
2.  Manager endpoint is used for registering the agent and worker endpoint for logs. Is ossec config your manager elb endpoint would be there. 
3. There is also issue when you use TCP or UDP. When you registered the agent did you use UDP or TCP.

**Comment by Born2Bake** [comment]
> Can you share the ossec config?
> 
> This can be because of below
> 
> 1. I hope you are aware that registration url and logs url are different.
> 2. Manager endpoint is used for registering the agent and worker endpoint for logs. Is ossec config your manager elb endpoint would be there.
> 3. There is also issue when you use TCP or UDP. When you registered the agent did you use UDP or TCP.

Hi,

Thank you for your response.

Ansible config:
```
---
- hosts: wazuh-agents
  roles:
    - roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_custom_packages_installation_agent_enabled: true
    wazuh_custom_packages_installation_agent_rpm_url: "https://packages.wazuh.com/3.x/yum/wazuh-agent-3.12.0-1.x86_64.rpm"
    ##wazuh_custom_packages_installation_agent_deb_url: ""
    wazuh_managers:
      - address: internal-1.elb.amazonaws.com.
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: foo
    wazuh_agent_authd:
      registration_address: internal-2.elb.amazonaws.com
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
```

Ossec:

```
<ossec_config>
  <client>
    <server>
      <address>internal-1.elb.amazonaws.com.</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>centos, centos7, centos7.6</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
  </client>
```
Ossec logs on machine:

```
2020/07/27 08:34:19 ossec-agentd: INFO: Trying to connect to server (internal-1.elb.amazonaws.com./172.31.85.91:1514/tcp).
2020/07/27 08:34:19 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'internalt-1.elb.amazonaws.com./172.31.85.91'.
```

So agents can be registered but they cannot talk to 1514 elb for some reason.
