### ISSUE TITLE
MVP - Modify deployment configuration in Kubernetes

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-kubernetes#948]
## Description

This task requires adjusting the Wazuh deployment in Kubernetes by removing all the configuration file templates used. These modifications must be made to the configuration files that Wazuh brings within the image.

These are the configuration files currently used:

``` yaml
configMapGenerator:
  - name: indexer-conf
    files:
      - indexer_stack/wazuh-indexer/indexer_conf/opensearch.yml
      - indexer_stack/wazuh-indexer/indexer_conf/internal_users.yml
  - name: wazuh-conf
    files:
      - wazuh_managers/wazuh_conf/master.conf
      - wazuh_managers/wazuh_conf/worker.conf
  - name: dashboard-conf
    files:
      - indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml
```

The use of environment variables will depend especially on the possibilities offered by the Wazuh server 5.0.0 image.

## Tasks

- [ ] Remove all configuration files mounted in the Wazuh deployment

- [ ] Use environment variables to configure the minimum parameters for a successful deployment
